### ISSUE TITLE
Cant install this extension with VS Community 2019

### ISSUE THREAD

**Issue by Surrogate-TM** [nbelyh/IdMsoAutocomplete#4]
Hi, Nikolay !
I download this extension at [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=NikolayBelyh.IdMsoAutocompletevs2017)
When I start installation, I get error. Log in attachment.
[dd_VSIXInstaller_20220405102125_24dc.log](https://github.com/nbelyh/IdMsoAutocomplete/files/8415862/dd_VSIXInstaller_20220405102125_24dc.log)

**Comment by nbelyh** [comment]
Yes, I (still) have not published the update on marketplace. Forgot back then, and now it needs already update for Visual Studio 2022. The update was available here in "releases". Will check.

**Comment by Surrogate-TM** [comment]
I download this repository and try 'release'. I get errors. In some configurations few files are absend, for example: _Keys.snk_ and _packages.config_

**Comment by nbelyh** [comment]
@Surrogate-TM I've restored the release (1.0.3). Could you please try if it installs now?
https://github.com/nbelyh/IdMsoAutocomplete/releases/download/1.0.3/IdMsoAutocomplete.2019.vsix

**Comment by Surrogate-TM** [comment]
@nbelyh Thank you, I installed this extension now!
But dropbox with imageMso dont works…
![AutoComplit](https://user-images.githubusercontent.com/35092915/162687729-ed3f4b21-d719-4e4a-897e-f7699c94faad.png)

**Comment by nbelyh** [comment]
@Surrogate-TM could you please change "Office 2019" to "Office 2016", seems to be a bug (there are no icons available for the Office 2019). In the settings menu (Tools => Options):

![image](https://user-images.githubusercontent.com/528366/162693034-bea4814e-f156-4650-8bb1-6d8f5bc205d9.png)

I mean, no icons for Office 2019 exist in the app, this is still to do as another item... But since the office is upward compatible, most of the icons are the same as in 2016 (since only names are used)

**Comment by Surrogate-TM** [comment]
@nbelyh Cool, After this change everything is working ! Thanks again !!!
This issue can be closed :)

**Comment by nbelyh** [comment]
@Surrogate-TM Still need to either remove "Office 2019" from the menu or (better) to add icons for Office 2019... :)
Also upload to the VS Marketplace after that..

**Comment by Surrogate-TM** [comment]
Does office 2019 have its own specific icons?

**Comment by nbelyh** [comment]
@Surrogate-TM  I don't know for sure, but just **think** that it probably does 😄
